[package]
name = "miq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
bytes = "1.4.0"
clap = { version = "4.1.8", features = [
    "derive",
    "env",
] }
fern = "0.6.1"
log = "0.4.17"
reqwest = { version = "0.11.14", default-features = false, features = [
    "rustls-tls",
    "blocking",
] }
schemars = "0.8.12"
serde = { version = "1.0.154", features = [
    "derive",
] }
serde_dhall = { version = "0.12.1", default-features = false, features = [
] }
serde_json = "1.0.94"
tempfile = "3.4.0"
toml = "0.7.2"
unshare = "0.7.0"
