#:schema ./schema.json
fetch = [
]

[[pkg]]
path = "/miq/store/AAAH-trivial"
name = "trivial"
version = "none"
script = """
set -eux
tee main.c <<EOF
#include <stdio.h>
#include <stdlib.h>

int main() {
  printf("Hello World");
  exit(0);
}
EOF

tee ld <<EOF
#!/bin/sh
echo "Custom LD running!"
exec /home/ayats/Documents/miq/devel/nix-bootstrap/bin/ld \
  -z relro \
  -z now \
  -dynamic-linker /miq/store/AAAE-musl-1.2.3/lib/ld-musl-x86_64.so.1 \
  "\\${@}" \
  -L/miq/store/AAAE-musl-1.2.3/lib
EOF

chmod +x ld
export PATH="$PWD:$PATH"
cat $(command -v ld)
ld --version



$CC \
  -fPIC \
  -nostdinc \
  -Wimplicit-function-declaration \
  -Werror=implicit-function-declaration \
  -isystem /miq/store/AAAE-musl-1.2.3/include \
  main.c -o $miq_out \
  -B/miq/store/AAAE-musl-1.2.3/lib \
  -idirafter /miq/store/AAAE-musl-1.2.3/include

"""
bdeps_buildm = [
]
bdeps_hostm = [
]
rdeps_hostm = [
]
[pkg.env]
PATH = "/home/ayats/Documents/miq/devel/nix-bootstrap/bin:/miq/store/AAAE-musl-1.2.3/bin:/miq/store/AAAA-zig-0.11.0/zig"
CC = "/miq/store/AAAA-zig-0.11.0/zig cc"
# CFLAGS = "-O2 -pipe -fPIC -Wl\\,-dynamic-linker=/miq/store/AAAE-musl-1.2.3/bin/ld.musl-clang"
# LD_FLAGS = "-rpath /miq/store/AAAG-dash-0.5.12/lib -L/miq/store/AAAE-musl-1.2.3/lib -t"
