#:schema ./schema.json
fetch = [
]

[[pkg]]
path = "/miq/store/AAAH-trivial"
name = "trivial"
version = "none"
script = """
set -eux

tee main.c <<EOF
#include <stdio.h>
#include <stdlib.h>
int main() {
  printf("Hello World");
  exit(0);
}

EOF


tee ./ld <<EOF
#!/bin/sh
echo "Custom LD running!"
exec /miq/store/AABB-bootstrap/bin/ld \
  -dynamic-linker /miq/store/AABB-bootstrap/lib/ld-musl-x86_64.so.1 \
  "\\${@}" \
  -rpath /miq/store/AABB-bootstrap/lib \
  -L/miq/store/AABB-bootstrap/lib
EOF

chmod +x ld
export PATH="$PWD:$PATH"
command -v ld

$CC -print-prog-name=ld

$CC \
  $CFLAGS \
  -Wl,-dynamic-linker=/miq/store/AABB-bootstrap/lib/ld-musl-x86_64.so.1 \
  main.c -o $miq_out \
  -B/miq/store/AABB-bootstrap/lib \
  -idirafter /miq/store/AABB-bootstrap/include-libc \
  -isystem /miq/store/AABB-bootstrap/include-libc

"""
bdeps_buildm = [
]
bdeps_hostm = [
]
rdeps_hostm = [
]
[pkg.env]
PATH = "/miq/store/AABB-bootstrap/bin"
CC = "/miq/store/AABB-bootstrap/bin/gcc"
CFLAGS = "-O2 -pipe -pie -fPIE -fPIC"