#:schema ./schema.json
[[pkg]]
name = "zig"
version = "0.11.0"
script = """
set -x
mkdir -pv $miq_out
rm -rvf $miq_out/*
rm -rvf $miq_out/.*
cd $miq_out
tar -xv --strip-components 1 -f $miq_fetch
"""
path = "/miq/store/AAAA-zig-0.11.0"

[pkg.env]
PATH="/home/ayats/Documents/miq/devel/nix-bootstrap/bin"

[[pkg.fetch]]
url = "https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.1932+c93e0d861.tar.xz"
hash = "FIXME"
