#:schema ./schema.json
[[fetch]]
path = "/miq/store/AAAB-zig-0.11.0.tar.gz"
url = "https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.1932+c93e0d861.tar.xz"
hash = "FIXME"


[[pkg]]
path = "/miq/store/AAAA-zig-0.11.0"
name = "zig"
version = "0.11.0"
script = """
set -x
mkdir -pv $miq_out
cd $miq_out
tar -xv --strip-components 1 -f $miq_fetch
"""
bdeps_buildm = [
    "/miq/store/AAAB-zig-0.11.0.tar.gz",
]
bdeps_hostm = [
]
rdeps_hostm = [
]
[pkg.env]
PATH = "/home/ayats/Documents/miq/devel/nix-bootstrap/bin"
miq_fetch = "/miq/store/AAAB-zig-0.11.0.tar.gz"
