# -*- mode: plaintext -*-

default:
  just --list

flags := "-xelatex -synctex=1 -interaction=nonstopmode --file-line-error --shell-escape -outdir=out -aux-directory=aux"

file := "index.tex"

build:
  latexmk {{flags}} {{file}}

watch:
  latexmk {{flags}} -pvc -view=none {{file}}

clean:
  rm -rvf out
  rm -rvf aux
  rm -rvf _minted-index
  rm -rvf svg-inkscape

copy-bib:
  cp -vfL ~/Documents/miq.bib miq.bib
  chmod 644 miq.bib

sync:
  rsync -arvP --no-perms --no-owner --no-group --delete --no-times ~/Documents/miq-share/ assets

graph:

