# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: Build and release

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

permissions:
  contents: write

concurrency: build

jobs:
  miq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Install Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build miq
        run: |
          mkdir release
          nix build .#pkgsCross.musl64.miq -L
          cp -vL ./result/bin/miq release

          for file in pkgs/*.lua; do
            cp -v "$file" release
          done

          cd release
          tar -czvf release.tar.gz --sort=name --owner=root:0 --group=root:0 --mtime='1970-01-01' *

      - uses: ncipollo/release-action@v1
        name: Release
        with:
          tag: latest
          omitBody: true
          omitName: true
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "release/release.tar.gz,release/miq"

  doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Install Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build doc
        run: |
          pushd doc
          nix develop .#doc --command just build
          popd

      - uses: ncipollo/release-action@v1
        name: Release
        with:
          tag: latest
          omitBody: true
          omitName: true
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "doc/out/index.pdf"
